export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <main className="flex-1">{children}</main>

          <footer
            style={{ background: "darkblue", padding: "1rem", color: "white" }}
          >
            Footer
          </footer>
        </div>
      </body>
    </html>
  );
}
